name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Instalar cloudflared
        run: |
          curl -L --output cloudflared.deb \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Configurar SSH
        run: |
          cat <<EOF > ~/.ssh/config
          Host ssh.bokargiu.com.br
              User bokargiu
              IdentityFile ~/.ssh/id_ed25519
              ProxyCommand cloudflared access ssh \
                --hostname %h \
                --service-token-id "${{ secrets.CF_ACCESS_CLIENT_ID }}" \
                --service-token-secret "${{ secrets.CF_ACCESS_CLIENT_SECRET }}"
          EOF

          chmod 600 ~/.ssh/config

      - name: Testar servidor
        run: |
          ssh -o BatchMode=yes \
          -o StrictHostKeyChecking=no \
          ssh.bokargiu.com.br \
          "whoami && docker --version && docker compose version"

      - name: Testar projeto
        run: |
          ssh -o BatchMode=yes \
              -o StrictHostKeyChecking=no \
              ssh.bokargiu.com.br \
              "cd ~/Portifolio/Portifolio && git status"

      - name: Deploy
        run: |
          ssh -o BatchMode=yes \
              -o StrictHostKeyChecking=no \
              ssh.bokargiu.com.br \
              "cd ~/Portifolio/Portifolio && git pull --ff-only origin master && docker compose down && docker compose up -d --build"
